# Generated by Django 4.0.1 on 2022-01-26 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone numbers must be 10 digits. Please omit the country code.', regex='^\\d{10}$')])),
                ('house_number', models.PositiveIntegerField()),
                ('address_line_1', models.CharField(default=None, max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(default=None, max_length=20)),
                ('state', models.CharField(default=None, max_length=20)),
                ('country', models.CharField(default=None, max_length=20)),
                ('pincode', models.CharField(default=None, max_length=6)),
            ],
        ),
    ]
