# Generated by Django 4.0.1 on 2022-01-26 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address_line_1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default=None, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone numbers must be 10 digits. Please omit the country code.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
