# Generated by Django 4.0.1 on 2022-01-26 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressapi', '0002_alter_contact_address_line_1_alter_contact_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone numbers must be 10 digits. Please omit the country code.', regex='^\\d{10}$')]),
        ),
    ]
